workflows:
  android-build:
    name: BoosterFA7 Gradle APK
    max_build_duration: 15
    environment:
      vars:
        JAVA_VERSION: 11
    scripts:
      - ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - npo.fa@outlook.com